-- Creating Table 1 -- Customer Table

DROP TABLE IF EXISTS Customer;
CREATE TABLE IF NOT EXISTS Customer
(

	Customer_id	VARCHAR(10) PRIMARY KEY, 
	Customer_name VARCHAR(50),
	City VARCHAR(20),
	Customer_type VARCHAR(20)

);

SELECT * FROM Customer;

-- Importing data from csv file
COPY
Customer(Customer_id,	Customer_name,	City,	Customer_type)
FROM 'D:\SQL\Practice Files\Excel Files\Customer_Data_For Joins.csv'
DELIMITER','
CSV HEADER;

-- Creating Table 2 : Product Table

DROP TABLE IF EXISTS Product;
CREATE TABLE IF NOT EXISTS Product
(

	Customer_id	VARCHAR(10) PRIMARY KEY, 
	Product	VARCHAR(50),
	Price money
);

SELECT * FROM Product;

-- Importing data from csv file

COPY
Product(Customer_id,	Product,	Price)
FROM 'D:\SQL\Practice Files\Excel Files\Product and Sales Table _ for Joins.csv'
DELIMITER','
CSV HEADER;


-- INNER JOIN

SELECT * 
FROM CUSTOMER AS C
INNER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;

-- GET SPEICIFIC COLUMN
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
INNER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;


-- LEFT JOIN

SELECT * 
FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID=P.CUSTOMER_ID;


-- GET SPEICIFIC COLUMN
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;


-- RIGHT JOIN

SELECT * 
FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P
ON C.CUSTOMER_ID=P.CUSTOMER_ID;

-- GET SPEICIFIC COLUMN
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;



-- FULL OUTER JOIN

SELECT * 
FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID=P.CUSTOMER_ID;

-- GET SPEICIFIC COLUMN
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;


--JOINS WITH WHERE CLAUSE
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE P.CUSTOMER_ID IS NOT NULL;


SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NOT NULL;


SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NOT NULL AND P.CUSTOMER_ID IS NOT NULL;



-- SELFT JOIN

-- Creating Table 3 -- Salesman

DROP TABLE IF EXISTS Salesman;
CREATE TABLE IF NOT EXISTS Salesman
(

	emp_id	VARCHAR(10) PRIMARY KEY, 
	salesman_name VARCHAR(50),
	city VARCHAR(20),
	supervisor_id VARCHAR(10)

);

SELECT * FROM Salesman;

insert into Salesman (emp_id, salesman_name, city, supervisor_id)
 		values  ('S001', 'Sachin Jadhav', 'Mumbai', 'S002'),
				('S002', 'Adika Singh', 'Pune',  'S004'),
 				('S003', 'Vijay More', 'Delhi', 'S002'),
 				('S004', 'Atul Kale', 'Mumbai', 'S004');
				
				

SELECT T2.SALESMAN_NAME AS SALESMAN, T1.SALESMAN_NAME AS SUPERVISOR
FROM SALESMAN AS T1
JOIN SALESMAN AS T2
ON T1.EMP_ID = T2.SUPERVISOR_ID;



--UNION AND UNION ALL

DROP TABLE IF EXISTS Salesman1;
CREATE TABLE IF NOT EXISTS Salesman1
(
	emp_id	VARCHAR(10) PRIMARY KEY, 
	salesman_name VARCHAR(50),
	city VARCHAR(20)
);

SELECT * FROM Salesman1;

insert into Salesman1 (emp_id, salesman_name, city)
 		values  ('S001', 'Sachin Jadhav', 'Mumbai'),
				('S002', 'Adika Singh', 'Pune'),
 				('S003', 'Vijay More', 'Delhi' ),
 				('S004', 'Atul Kale', 'Mumbai' );
				
				
DROP TABLE IF EXISTS Salesman2;
CREATE TABLE IF NOT EXISTS Salesman2
(

	emp_id	VARCHAR(10) PRIMARY KEY, 
	salesman_name VARCHAR(50),
	city VARCHAR(20)


);

SELECT * FROM Salesman2;

insert into Salesman2 (emp_id, salesman_name, city)
 		values  ('S004', 'Atul Kale', 'Mumbai'),
				('S005', 'Vinod Mehra', 'Nagpur'),
 				('S006', 'Ajay Shetty', 'Surat' ),
 				('S007', 'Abdul Shaikh', 'Mumbai' );

SELECT * FROM SALESMAN1
UNION
SELECT * FROM SALESMAN2;

SELECT * FROM SALESMAN1
UNION ALL
SELECT * FROM SALESMAN2;




